author: J. Morgan Lieberthal
github_url: https://github.com/baberthal/MemoryBuffer

theme: fullwidth
clean: true
min_acl: private
docset_path: MemoryBuffer.docset

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-scheme, MemoryBuffer]
